{% set name = "cythonbiogeme" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cythonbiogeme-{{ version }}.tar.gz
  sha256: 1e869d482d51fde70bdb88a52207a30081f2ef0d9ee8a5b0f7df850cae4d1719

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3.0.10
    - numpy >=2
    - pip
    - python
    - setuptools >=70.1.1
    - wheel >=0.43.0
  run:
    - python
    - numpy

test:
  imports:
    - cythonbiogeme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/michelbierlaire/cythonbiogeme
  summary: C++ part of the Biogeme package
  license: Custom
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
